// The habit library: a fixed catalogue of common habits, with the wording the
// model is shown when one of them has to be priced.
//
// Why this lives on the server as well as in the client: the price of a habit
// must not come from the client. Every EXP entry can name the price it was
// paid against (see the priceId check in index.js), and a price the client
// simply asserts is worth nothing as a check. So the client sends an id, and
// the server decides what that id is worth.
//
// What is editorial and what is judged, kept apart on purpose:
//
//   editorial — title, emoji, unit, amount, default schedule, and which
//               intelligences and traits the habit builds. These are taxonomy
//               decisions with a right answer; asking a model to re-derive
//               "drinking water is bodily" every time buys nothing. Every
//               category and trait named here is one from the app's own
//               index, never a new one invented for a preset.
//   judged    — `pt`, the EXP one repeat is worth. That is the number that has
//               to sit on the same scale as every hand-written task, so it
//               comes from the same evaluator, and is then cached per habit
//               and schedule so it is asked once rather than once per person
//               per tap.
//
// Ids are permanent: a stored price and a user's task both point at one.
// Changing what an id means would silently reprice somebody's habit.

const PRESETS = [
  // ---- body ----
  {
    id: "water",
    category: "body",
    emoji: "💧",
    title: "Drink water",
    description: "Drink two litres of water across the day, spread out rather than all at once.",
    unit: "L",
    targetAmount: 2,
    schedule: { type: "daily" },
    types: ["bodily"],
    traitTargets: [{ category: "bodily", trait: "Health" }],
  },
  {
    id: "steps",
    category: "body",
    emoji: "🚶",
    title: "Walk 8,000 steps",
    description: "Walk eight thousand steps over the course of the day, on top of normal moving around.",
    unit: "steps",
    targetAmount: 8000,
    schedule: { type: "daily" },
    types: ["bodily"],
    traitTargets: [{ category: "bodily", trait: "Daily exercise" }],
  },
  {
    id: "workout",
    category: "body",
    emoji: "🏋️",
    title: "Train",
    description: "A deliberate training session of about forty-five minutes: weights, a class, or hard cardio.",
    unit: "min",
    targetAmount: 45,
    schedule: { type: "weekdays", days: [1, 3, 5] },
    types: ["bodily"],
    traitTargets: [{ category: "bodily", trait: "Sports" }],
  },
  {
    id: "stretch",
    category: "body",
    emoji: "🧘",
    title: "Stretch",
    description: "Ten minutes of stretching or mobility work, enough to loosen up rather than a full session.",
    unit: "min",
    targetAmount: 10,
    schedule: { type: "daily" },
    types: ["bodily"],
    traitTargets: [{ category: "bodily", trait: "Yoga" }],
  },
  {
    id: "sleepEarly",
    category: "body",
    emoji: "🌙",
    title: "Sleep on time",
    description: "Be in bed by a set hour with the phone away, rather than drifting past midnight.",
    unit: "times",
    targetAmount: 1,
    schedule: { type: "daily" },
    types: ["bodily", "self"],
    traitTargets: [{ category: "bodily", trait: "Health" }, { category: "self", trait: "Self-motivation" }],
  },
  {
    id: "cookHome",
    category: "body",
    emoji: "🍳",
    title: "Cook at home",
    description: "Cook a proper meal at home instead of ordering in or eating out.",
    unit: "times",
    targetAmount: 1,
    schedule: { type: "perWeek", n: 4 },
    types: ["bodily"],
    traitTargets: [{ category: "bodily", trait: "Health" }],
  },
  {
    id: "outdoors",
    category: "body",
    emoji: "🌿",
    title: "Get outdoors",
    description: "Spend an hour outside away from buildings — a park, a trail, the sea — not a walk between errands.",
    unit: "min",
    targetAmount: 60,
    schedule: { type: "perWeek", n: 1 },
    types: ["natural", "bodily"],
    traitTargets: [{ category: "natural", trait: "Outdoor activities" }],
  },

  // ---- mind ----
  {
    id: "read",
    category: "mind",
    emoji: "📚",
    title: "Read",
    description: "Read twenty pages of a book, attentively enough to follow the argument.",
    unit: "pages",
    targetAmount: 20,
    schedule: { type: "daily" },
    types: ["linguistic"],
    traitTargets: [{ category: "linguistic", trait: "Reading" }],
  },
  {
    id: "meditate",
    category: "mind",
    emoji: "🕯️",
    title: "Meditate",
    description: "Ten minutes of sitting meditation, following the breath and returning to it when the mind wanders.",
    unit: "min",
    targetAmount: 10,
    schedule: { type: "daily" },
    types: ["self"],
    traitTargets: [{ category: "self", trait: "Reflection & thinking" }],
  },
  {
    id: "journal",
    category: "mind",
    emoji: "📝",
    title: "Journal",
    description: "Write a page about the day: what happened, what it felt like, and what to do differently.",
    unit: "times",
    targetAmount: 1,
    schedule: { type: "daily" },
    types: ["self", "linguistic"],
    traitTargets: [{ category: "self", trait: "Self-evaluation" }, { category: "linguistic", trait: "Writing" }],
  },
  {
    id: "language",
    category: "mind",
    emoji: "🗣️",
    title: "Practise a language",
    description: "Fifteen minutes of deliberate practice in a language being learned: vocabulary, listening, or speaking.",
    unit: "min",
    targetAmount: 15,
    schedule: { type: "daily" },
    types: ["linguistic"],
    traitTargets: [{ category: "linguistic", trait: "Language learning" }],
  },
  {
    id: "noPhoneMorning",
    category: "mind",
    emoji: "📵",
    title: "Phone-free first hour",
    description: "Keep off the phone for the first hour after waking: no feeds, no messages, no news.",
    unit: "times",
    targetAmount: 1,
    schedule: { type: "daily" },
    types: ["self"],
    traitTargets: [{ category: "self", trait: "Self-motivation" }],
  },

  // ---- work ----
  {
    id: "deepWork",
    category: "work",
    emoji: "🎯",
    title: "Deep work",
    description: "One uninterrupted hour on the hardest thing on the list, with notifications off.",
    unit: "min",
    targetAmount: 60,
    schedule: { type: "weekdays", days: [1, 2, 3, 4, 5] },
    types: ["self"],
    traitTargets: [{ category: "self", trait: "Time management" }],
  },
  {
    id: "study",
    category: "work",
    emoji: "📖",
    title: "Study",
    description: "Forty-five minutes of studying course material: reading, problems, or working through notes.",
    unit: "min",
    targetAmount: 45,
    schedule: { type: "perWeek", n: 5 },
    types: ["self", "logical"],
    traitTargets: [{ category: "self", trait: "Time management" }],
  },
  {
    id: "code",
    category: "work",
    emoji: "💻",
    title: "Build something",
    description: "Forty-five minutes writing code or building on a personal project, outside of work hours.",
    unit: "min",
    targetAmount: 45,
    schedule: { type: "perWeek", n: 4 },
    types: ["logical"],
    traitTargets: [{ category: "logical", trait: "Programming" }],
  },
  {
    id: "planDay",
    category: "work",
    emoji: "🗒️",
    title: "Plan the day",
    description: "Five minutes at the start of the day deciding what actually has to get done, and in what order.",
    unit: "min",
    targetAmount: 5,
    schedule: { type: "weekdays", days: [1, 2, 3, 4, 5] },
    types: ["self"],
    traitTargets: [{ category: "self", trait: "Personal goal-setting" }],
  },
  {
    id: "weekReview",
    category: "work",
    emoji: "🧭",
    title: "Weekly review",
    description: "Twenty minutes at the end of the week looking back at what moved and what stalled, and setting the next week.",
    unit: "min",
    targetAmount: 20,
    schedule: { type: "perWeek", n: 1 },
    types: ["self"],
    traitTargets: [{ category: "self", trait: "Self-evaluation" }],
  },


  // ---- people ----
  {
    id: "callFamily",
    category: "people",
    emoji: "📞",
    title: "Call family",
    description: "A real phone call to a parent or close relative, long enough to actually catch up.",
    unit: "times",
    targetAmount: 1,
    schedule: { type: "perWeek", n: 2 },
    types: ["social"],
    traitTargets: [{ category: "social", trait: "Social interaction" }],
  },
  {
    id: "seeFriends",
    category: "people",
    emoji: "🤝",
    title: "See a friend",
    description: "Meet a friend in person — coffee, a walk, a meal — rather than only messaging.",
    unit: "times",
    targetAmount: 1,
    schedule: { type: "perWeek", n: 1 },
    types: ["social"],
    traitTargets: [{ category: "social", trait: "Participating in social activities" }],
  },
  {
    id: "volunteer",
    category: "people",
    emoji: "🫱",
    title: "Volunteer",
    description: "Two hours of volunteering: helping at a charity, a mosque, a shelter, or a community project.",
    unit: "hr",
    targetAmount: 2,
    schedule: { type: "perMonth", n: 1 },
    types: ["social"],
    traitTargets: [{ category: "social", trait: "Volunteering" }],
  },

  // ---- home ----
  {
    id: "tidy",
    category: "home",
    emoji: "🧹",
    title: "Tidy up",
    description: "Ten minutes putting the place back in order: surfaces cleared, dishes done, things away.",
    unit: "min",
    targetAmount: 10,
    schedule: { type: "daily" },
    types: ["self"],
    traitTargets: [{ category: "self", trait: "Self-motivation" }],
  },
  {
    id: "laundry",
    category: "home",
    emoji: "🧺",
    title: "Laundry",
    description: "A full round of laundry: washed, dried, folded and put away, not left in the machine.",
    unit: "times",
    targetAmount: 1,
    schedule: { type: "perWeek", n: 1 },
    types: ["self"],
    traitTargets: [{ category: "self", trait: "Self-motivation" }],
  },
  {
    id: "budget",
    category: "home",
    emoji: "🧾",
    title: "Check the budget",
    description: "Go through the month's spending against what was planned, and adjust the plan.",
    unit: "times",
    targetAmount: 1,
    schedule: { type: "perMonth", n: 1 },
    types: ["logical", "self"],
    traitTargets: [{ category: "logical", trait: "Data analysis" }],
  },

  // ---- craft ----
  {
    id: "instrument",
    category: "craft",
    emoji: "🎹",
    title: "Practise an instrument",
    description: "Twenty minutes of practice on an instrument: scales, a piece, or working through a difficult passage.",
    unit: "min",
    targetAmount: 20,
    schedule: { type: "perWeek", n: 4 },
    types: ["musical"],
    traitTargets: [{ category: "musical", trait: "Playing an instrument" }],
  },
  {
    id: "draw",
    category: "craft",
    emoji: "✏️",
    title: "Draw",
    description: "Fifteen minutes of drawing from life or from imagination, finished or not.",
    unit: "min",
    targetAmount: 15,
    schedule: { type: "perWeek", n: 3 },
    types: ["visual"],
    traitTargets: [{ category: "visual", trait: "Drawing" }],
  },
  {
    id: "photo",
    category: "craft",
    emoji: "📷",
    title: "Take photographs",
    description: "Go out and shoot deliberately for half an hour, choosing what to frame rather than snapping what passes.",
    unit: "min",
    targetAmount: 30,
    schedule: { type: "perWeek", n: 1 },
    types: ["visual"],
    traitTargets: [{ category: "visual", trait: "Photography" }],
  },

  // ---- added later: a wider catalogue ----
  {
    id: "run",
    category: "body",
    emoji: "🏃",
    title: "Run",
    description: "A five-kilometre run at a steady pace, outdoors or on a treadmill.",
    unit: "km",
    targetAmount: 5,
    schedule: { type: "perWeek", n: 3 },
    types: ["bodily"],
    traitTargets: [{ category: "bodily", trait: "Sports" }],
  },
  {
    id: "pushups",
    category: "body",
    emoji: "💪",
    title: "Push-ups",
    description: "Thirty push-ups in the day, in as many sets as it takes.",
    unit: "reps",
    targetAmount: 30,
    schedule: { type: "daily" },
    types: ["bodily"],
    traitTargets: [{ category: "bodily", trait: "Daily exercise" }],
  },
  {
    id: "veggies",
    category: "body",
    emoji: "🥗",
    title: "Eat vegetables",
    description: "Two proper servings of vegetables across the day's meals.",
    unit: "times",
    targetAmount: 2,
    schedule: { type: "daily" },
    types: ["bodily"],
    traitTargets: [{ category: "bodily", trait: "Health" }],
  },
  {
    id: "sleep8",
    category: "body",
    emoji: "😴",
    title: "Sleep eight hours",
    description: "Eight hours of sleep in one stretch, not counting naps.",
    unit: "hr",
    targetAmount: 8,
    schedule: { type: "daily" },
    types: ["bodily"],
    traitTargets: [{ category: "bodily", trait: "Health" }],
  },
  {
    id: "coldShower",
    category: "body",
    emoji: "🚿",
    title: "Cold shower",
    description: "Finish the shower with a couple of minutes of cold water.",
    unit: "times",
    targetAmount: 1,
    schedule: { type: "daily" },
    types: ["bodily", "self"],
    traitTargets: [{ category: "bodily", trait: "Health" }, { category: "self", trait: "Self-motivation" }],
  },
  {
    id: "swim",
    category: "body",
    emoji: "🏊",
    title: "Swim",
    description: "Half an hour of swimming laps, not counting rest at the wall.",
    unit: "min",
    targetAmount: 30,
    schedule: { type: "perWeek", n: 2 },
    types: ["bodily"],
    traitTargets: [{ category: "bodily", trait: "Sports" }],
  },
  {
    id: "cycle",
    category: "body",
    emoji: "🚴",
    title: "Cycle",
    description: "Ten kilometres on a bicycle, as exercise rather than as transport.",
    unit: "km",
    targetAmount: 10,
    schedule: { type: "perWeek", n: 2 },
    types: ["bodily"],
    traitTargets: [{ category: "bodily", trait: "Sports" }],
  },
  {
    id: "selfDefense",
    category: "body",
    emoji: "🥋",
    title: "Martial arts practice",
    description: "A forty-five-minute martial arts or self-defence session.",
    unit: "min",
    targetAmount: 45,
    schedule: { type: "perWeek", n: 2 },
    types: ["bodily"],
    traitTargets: [{ category: "bodily", trait: "Self-defense techniques" }],
  },
  {
    id: "gratitude",
    category: "mind",
    emoji: "🙏",
    title: "Write three things you are grateful for",
    description: "Write down three specific things from today that went well.",
    unit: "times",
    targetAmount: 1,
    schedule: { type: "daily" },
    types: ["self"],
    traitTargets: [{ category: "self", trait: "Reflection & thinking" }],
  },
  {
    id: "podcast",
    category: "mind",
    emoji: "🎧",
    title: "Listen to a talk or podcast",
    description: "Twenty minutes of a lecture or podcast, listened to attentively.",
    unit: "min",
    targetAmount: 20,
    schedule: { type: "perWeek", n: 4 },
    types: ["musical", "linguistic"],
    traitTargets: [{ category: "musical", trait: "Active listening" }],
  },
  {
    id: "puzzle",
    category: "mind",
    emoji: "🧩",
    title: "Solve puzzles",
    description: "Fifteen minutes on chess, sudoku or another thinking puzzle.",
    unit: "min",
    targetAmount: 15,
    schedule: { type: "perWeek", n: 4 },
    types: ["logical"],
    traitTargets: [{ category: "logical", trait: "Puzzle solving" }],
  },
  {
    id: "writeDaily",
    category: "mind",
    emoji: "✍️",
    title: "Write",
    description: "Twenty minutes of writing: an article, a story, or notes of your own.",
    unit: "min",
    targetAmount: 20,
    schedule: { type: "perWeek", n: 5 },
    types: ["linguistic"],
    traitTargets: [{ category: "linguistic", trait: "Writing" }],
  },
  {
    id: "noSocial",
    category: "mind",
    emoji: "📵",
    title: "A day without social media",
    description: "Get through the day without opening any social media app.",
    unit: "times",
    targetAmount: 1,
    schedule: { type: "daily" },
    types: ["self"],
    traitTargets: [{ category: "self", trait: "Time management" }],
  },
  {
    id: "wakeEarly",
    category: "mind",
    emoji: "⏰",
    title: "Wake up early",
    description: "Get up at the hour you set, without going back to sleep.",
    unit: "times",
    targetAmount: 1,
    schedule: { type: "daily" },
    types: ["self"],
    traitTargets: [{ category: "self", trait: "Time management" }],
  },
  {
    id: "inboxZero",
    category: "work",
    emoji: "📥",
    title: "Clear the inbox",
    description: "Deal with the day's messages so nothing is left unanswered.",
    unit: "times",
    targetAmount: 1,
    schedule: { type: "weekdays", days: [1, 2, 3, 4, 5] },
    types: ["self"],
    traitTargets: [{ category: "self", trait: "Time management" }],
  },
  {
    id: "studySkill",
    category: "work",
    emoji: "🎓",
    title: "Study a new skill",
    description: "Half an hour of deliberate study of a skill you are building.",
    unit: "min",
    targetAmount: 30,
    schedule: { type: "perWeek", n: 5 },
    types: ["self", "logical"],
    traitTargets: [{ category: "self", trait: "Personal goal-setting" }],
  },
  {
    id: "sideProject",
    category: "work",
    emoji: "🚀",
    title: "Work on the side project",
    description: "Forty-five minutes on your own project, building rather than planning.",
    unit: "min",
    targetAmount: 45,
    schedule: { type: "perWeek", n: 3 },
    types: ["logical"],
    traitTargets: [{ category: "logical", trait: "Programming" }],
  },
  {
    id: "networking",
    category: "work",
    emoji: "🔗",
    title: "Reach out to someone in your field",
    description: "Start one real conversation with somebody who works in your field.",
    unit: "times",
    targetAmount: 1,
    schedule: { type: "perWeek", n: 1 },
    types: ["social"],
    traitTargets: [{ category: "social", trait: "Effective communication" }],
  },
  {
    id: "readNews",
    category: "work",
    emoji: "📰",
    title: "Read about your field",
    description: "Fifteen minutes reading articles or research from your own field.",
    unit: "min",
    targetAmount: 15,
    schedule: { type: "weekdays", days: [1, 2, 3, 4, 5] },
    types: ["linguistic"],
    traitTargets: [{ category: "linguistic", trait: "Reading" }],
  },
  {
    id: "familyTime",
    category: "people",
    emoji: "👨‍👩‍👧",
    title: "Time with family, phones away",
    description: "Half an hour with family with no phone in anyone's hand.",
    unit: "min",
    targetAmount: 30,
    schedule: { type: "daily" },
    types: ["social"],
    traitTargets: [{ category: "social", trait: "Social interaction" }],
  },
  {
    id: "thankYouMsg",
    category: "people",
    emoji: "💌",
    title: "Send a message of thanks",
    description: "Tell one person, in your own words, what you appreciate about them.",
    unit: "times",
    targetAmount: 1,
    schedule: { type: "perWeek", n: 2 },
    types: ["social"],
    traitTargets: [{ category: "social", trait: "Effective communication" }],
  },
  {
    id: "helpSomeone",
    category: "people",
    emoji: "🤲",
    title: "Help someone",
    description: "Do something useful for somebody without being asked and without payment.",
    unit: "times",
    targetAmount: 1,
    schedule: { type: "perWeek", n: 1 },
    types: ["social"],
    traitTargets: [{ category: "social", trait: "Volunteering" }],
  },
  {
    id: "teachSomeone",
    category: "people",
    emoji: "👩‍🏫",
    title: "Teach or explain something",
    description: "Twenty minutes explaining something you know to somebody who does not.",
    unit: "min",
    targetAmount: 20,
    schedule: { type: "perWeek", n: 1 },
    types: ["social", "linguistic"],
    traitTargets: [{ category: "social", trait: "Effective communication" }],
  },
  {
    id: "dishes",
    category: "home",
    emoji: "🍽️",
    title: "Wash up straight after eating",
    description: "Clear and wash the dishes right after the meal instead of later.",
    unit: "times",
    targetAmount: 1,
    schedule: { type: "daily" },
    types: ["self"],
    traitTargets: [{ category: "self", trait: "Time management" }],
  },
  {
    id: "declutter",
    category: "home",
    emoji: "📦",
    title: "Clear out one spot",
    description: "Fifteen minutes emptying one drawer, shelf or corner properly.",
    unit: "min",
    targetAmount: 15,
    schedule: { type: "perWeek", n: 1 },
    types: ["self"],
    traitTargets: [{ category: "self", trait: "Personal goal-setting" }],
  },
  {
    id: "mealPrep",
    category: "home",
    emoji: "🥘",
    title: "Prepare meals for the week",
    description: "An hour of cooking ahead so the week's meals are ready.",
    unit: "min",
    targetAmount: 60,
    schedule: { type: "perWeek", n: 1 },
    types: ["bodily"],
    traitTargets: [{ category: "bodily", trait: "Health" }],
  },
  {
    id: "groceries",
    category: "home",
    emoji: "🛒",
    title: "Shop with a list",
    description: "Do the week's shopping from a written list, in one trip.",
    unit: "times",
    targetAmount: 1,
    schedule: { type: "perWeek", n: 1 },
    types: ["self"],
    traitTargets: [{ category: "self", trait: "Time management" }],
  },
  {
    id: "sing",
    category: "craft",
    emoji: "🎤",
    title: "Sing",
    description: "Fifteen minutes of singing practice: warm-ups and a song worked on.",
    unit: "min",
    targetAmount: 15,
    schedule: { type: "perWeek", n: 3 },
    types: ["musical"],
    traitTargets: [{ category: "musical", trait: "Vocal training" }],
  },
  {
    id: "compose",
    category: "craft",
    emoji: "🎼",
    title: "Write music",
    description: "Twenty minutes making something of your own: a melody, a beat, a part.",
    unit: "min",
    targetAmount: 20,
    schedule: { type: "perWeek", n: 2 },
    types: ["musical"],
    traitTargets: [{ category: "musical", trait: "Musical creativity" }],
  },
  {
    id: "designPractice",
    category: "craft",
    emoji: "🎨",
    title: "Design practice",
    description: "Half an hour designing: a poster, an interface, or a study piece.",
    unit: "min",
    targetAmount: 30,
    schedule: { type: "perWeek", n: 2 },
    types: ["visual"],
    traitTargets: [{ category: "visual", trait: "Graphic design" }],
  },
  {
    id: "model3d",
    category: "craft",
    emoji: "🧱",
    title: "3D modelling practice",
    description: "Half an hour modelling or planning something in three dimensions.",
    unit: "min",
    targetAmount: 30,
    schedule: { type: "perWeek", n: 2 },
    types: ["visual"],
    traitTargets: [{ category: "visual", trait: "3D planning" }],
  },
  {
    id: "handcraft",
    category: "craft",
    emoji: "🧶",
    title: "Handcraft",
    description: "Half an hour of making something by hand: wood, thread, clay, repair.",
    unit: "min",
    targetAmount: 30,
    schedule: { type: "perWeek", n: 2 },
    types: ["bodily"],
    traitTargets: [{ category: "bodily", trait: "Handcrafts" }],
  },
  {
    id: "acting",
    category: "craft",
    emoji: "🎭",
    title: "Acting practice",
    description: "Twenty minutes rehearsing a scene, a monologue or improvisation.",
    unit: "min",
    targetAmount: 20,
    schedule: { type: "perWeek", n: 2 },
    types: ["bodily"],
    traitTargets: [{ category: "bodily", trait: "Acting" }],
  },
  {
    id: "plants",
    category: "nature",
    emoji: "🪴",
    title: "Tend the plants",
    description: "Water and look after the plants, indoors or in the garden.",
    unit: "times",
    targetAmount: 1,
    schedule: { type: "perWeek", n: 2 },
    types: ["natural"],
    traitTargets: [{ category: "natural", trait: "Farming & gardening" }],
  },
  {
    id: "walkOutdoors",
    category: "nature",
    emoji: "🌳",
    title: "Walk outdoors",
    description: "Half an hour walking outside, away from screens.",
    unit: "min",
    targetAmount: 30,
    schedule: { type: "perWeek", n: 3 },
    types: ["natural", "bodily"],
    traitTargets: [{ category: "natural", trait: "Outdoor activities" }],
  },
  {
    id: "natureLearn",
    category: "nature",
    emoji: "🔎",
    title: "Learn about nature",
    description: "Twenty minutes learning about plants, animals or the climate around you.",
    unit: "min",
    targetAmount: 20,
    schedule: { type: "perWeek", n: 1 },
    types: ["natural"],
    traitTargets: [{ category: "natural", trait: "Learning about the environment" }],
  },
  {
    id: "hike",
    category: "nature",
    emoji: "🥾",
    title: "Hike",
    description: "A couple of hours on a trail, out of the city.",
    unit: "hr",
    targetAmount: 2,
    schedule: { type: "perMonth", n: 2 },
    types: ["natural", "bodily"],
    traitTargets: [{ category: "natural", trait: "Outdoor activities" }, { category: "bodily", trait: "Sports" }],
  },
];

const CATEGORIES = ["body", "mind", "work", "people", "home", "craft", "nature"];

const BY_ID = new Map(PRESETS.map((p) => [p.id, p]));

function byId(id) {
  return typeof id === "string" ? BY_ID.get(id) || null : null;
}

// A short, stable string for one schedule, used as the cache key. Built from
// the fields that actually change the price, in a fixed order — an object's
// key order is not something to hang a cache on. The anchor date is
// deliberately left out: "every 3 days" is worth the same whichever day it
// starts on, and including it would give every user their own cache entry.
function scheduleKey(schedule) {
  const s = schedule && typeof schedule === "object" ? schedule : {};
  switch (s.type) {
    case "weekdays": return "weekdays-" + (s.days || []).join(".");
    case "perWeek": return "perWeek-" + s.n;
    case "monthDays": return "monthDays-" + (s.days || []).join(".");
    case "perMonth": return "perMonth-" + s.n;
    case "interval": return "interval-" + s.every;
    case "perInterval": return "perInterval-" + s.n + "-" + s.every;
    default: return "daily";
  }
}

// The client sends a schedule, so it is rebuilt here from scratch rather than
// trusted: this one decides a cache key and a price.
function sanitizeSchedule(raw) {
  const s = raw && typeof raw === "object" ? raw : {};
  const int = (v, lo, hi, fallback) => {
    const n = Math.round(Number(v));
    return Number.isFinite(n) ? Math.max(lo, Math.min(hi, n)) : fallback;
  };
  const list = (v, lo, hi) => {
    const out = [];
    (Array.isArray(v) ? v : []).forEach((x) => {
      const n = Math.round(Number(x));
      if (Number.isFinite(n) && n >= lo && n <= hi && out.indexOf(n) < 0) out.push(n);
    });
    return out.sort((a, b) => a - b);
  };
  switch (s.type) {
    case "weekdays": {
      const days = list(s.days, 0, 6);
      return days.length ? { type: "weekdays", days } : { type: "daily" };
    }
    case "perWeek": return { type: "perWeek", n: int(s.n, 1, 7, 3) };
    case "monthDays": {
      const days = list(s.days, 1, 31);
      return { type: "monthDays", days: days.length ? days : [1] };
    }
    case "perMonth": return { type: "perMonth", n: int(s.n, 1, 31, 4) };
    case "interval": return { type: "interval", every: int(s.every, 2, 365, 2) };
    case "perInterval": {
      const every = int(s.every, 2, 365, 10);
      return { type: "perInterval", every, n: int(s.n, 1, every, 1) };
    }
    default: return { type: "daily" };
  }
}

module.exports = { PRESETS, CATEGORIES, byId, scheduleKey, sanitizeSchedule };
